image: docker.paziresh24.info/node:14.18.2-alpine

stages:
  - test
  - build-image
  - deploy
  - rollback

variables:
  RULES_CHANGES_PATH: "**/*"
  DOCKER_IMAGE_TAG_LOCAL: docker.paziresh24.info/drapp-local
  DOCKER_IMAGE_TAG_COM: docker.paziresh24.info/drapp
  KUBERNETES_DOCKER_TAG: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-${CI_PIPELINE_ID}
  
  FF_USE_FASTZIP: "true"
  # These can be specified per job or per pipeline
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  ANSIBLE_FORCE_COLOR: 'true'

# Caches
.node_modules-cache: &node_modules-cache
  key:
    files:
      - yarn.lock
  paths:
    - node_modules
    - apps/*/node_modules/
  policy: pull

.yarn-cache: &yarn-cache
  key: yarn-$CI_JOB_IMAGE
  paths:
    - .yarn

cache:
  key: $CI_PROJECT_ID
  policy: pull
  untracked: true
  paths:
    - node_modules/
    - apps/drapp/node_modules/

before_script:
  - export DOCKER_BUILD=1

services:
  - name: docker.paziresh24.info/docker:dind
    alias: docker

.base-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
      changes:
        - $RULES_CHANGES_PATH


.drApp:
  extends: .base-rules
  variables:
    RULES_CHANGES_PATH: "apps/drapp/**/*"


.drApp-test:
  stage: test
  extends: .drApp
  script:
#    - npm config set registry http://192.168.216.74:8081/repository/npm-proxy/
    - apk update && apk add xvfb x11vnc fluxbox xdpyinfo st vim terminus-font \
      && sed -r -i "s/\[exec\] \(xterm\) \{xterm\}/\[exec\] \(st\) \{st -f 'xos4 Terminus-14'\}/" /usr/share/fluxbox/menu \
      && [[ ! -d /opt ]] && mkdir /opt \
      && rm -vrf /var/cache/apk/*
    - npm config get registry
    - npm install --prefer-offline --no-audit --force
    - npm run e2e-ci drapp-e2e
  cache:
    key: $CI_PROJECT_ID
    policy: pull-push
    paths:
      - yarn.lock
      - .yarn
      - node_modules
      - 'apps/*/node_modules'


.drApp-build-local-push-docker-image:
  stage: build-image
#  needs: ["drApp-test"]
  image: docker.paziresh24.info/docker:stable
  extends: .drApp
  before_script:
    - docker info
    - echo '192.168.216.16 dockerhub.paziresh24.com' >> /etc/hosts
  script:
    - export DOCKER_BUILD=1
    - export DOCKER_BUILDKIT=1
    - docker login $DOCKER_REGISTRY_URL -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
    - docker build -t $DOCKER_IMAGE_TAG_LOCAL:latest -t $DOCKER_IMAGE_TAG_LOCAL:$KUBERNETES_DOCKER_TAG -f Dockerfile.localCenter .
    - docker push $DOCKER_IMAGE_TAG_LOCAL:latest
    - docker push $DOCKER_IMAGE_TAG_LOCAL:$KUBERNETES_DOCKER_TAG
  tags:
    - france-loc


drApp-build-cloud-push-docker-image:
  stage: build-image
#  needs: ["drApp-test"]
  image: docker.paziresh24.info/docker:stable
  extends: .drApp
  before_script:
    - docker info
    - echo '192.168.216.16 dockerhub.paziresh24.com' >> /etc/hosts
  script:
    - export DOCKER_BUILD=1
    - export DOCKER_BUILDKIT=1
    - docker login $DOCKER_REGISTRY_URL -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
    - docker build -t $DOCKER_IMAGE_TAG_COM:latest -t $DOCKER_IMAGE_TAG_COM:$KUBERNETES_DOCKER_TAG -f Dockerfile.drApp .
    - docker push $DOCKER_IMAGE_TAG_COM:latest
    - docker push $DOCKER_IMAGE_TAG_COM:$KUBERNETES_DOCKER_TAG
  tags:
    - france-loc


drApp-deploy-production:
  image: docker.paziresh24.info/docker-ansible:latest
  stage: deploy
  when: manual
#  needs: ["drApp-test"]
  script:
    - apk add --update bash openssh sshpass
    - ansible-playbook ./ansible/drapp/playbook-com.yml -i ./ansible/drapp/inventory.yml -e 'ansible_python_interpreter=/usr/bin/python3'
    - curl -X POST -F variables[DOCKER_TAG_CLOUD]=${KUBERNETES_DOCKER_TAG} -F token=${KUBIT_WEBHOOK_TOKEN}  https://api.kubit.ir/api/core/packs/pai33lfy/vars/


.drApp-deploy-locals-kubernetes:
  image: docker.paziresh24.info/docker-ansible:latest
  stage: deploy
  when: manual
#  needs: ["drApp-test"]
  script:
    - curl -X POST -F variables[DOCKER_TAG_LOCAL]=${KUBERNETES_DOCKER_TAG} -F token=${KUBIT_WEBHOOK_TOKEN} https://api.kubit.ir/api/core/packs/pai33lfy/vars/


.drApp-deploy-locals:
  image: docker.paziresh24.info/docker-ansible:latest
  stage: deploy
  when: manual
#  needs: ["drApp-test"]
  script:
    - apk add --update bash openssh sshpass
    - ansible-playbook ./ansible/drapp/playbook-locals.yml -i ./ansible/drapp/inventory.yml -e 'ansible_python_interpreter=/usr/bin/python3'
#    - curl -X POST -F variables[DOCKER_TAG_LOCAL]=${KUBERNETES_DOCKER_TAG} -F token=${KUBIT_WEBHOOK_TOKEN} https://api.kubit.ir/api/core/packs/pai33lfy/vars/

drApp-rollback-production:
  image: docker.paziresh24.info/docker-ansible:latest
  stage: rollback
  when: manual
  #needs: ["drApp-deploy-production"]
  script:
    - apk add --update bash openssh sshpass
    - ansible-playbook ./ansible/drapp/playbook-com-rollback.yml -i ./ansible/drapp/inventory.yml -e 'ansible_python_interpreter=/usr/bin/python3'
