version: '3.7'

services:
    drapp:
        container_name: drapp
        # image: dockerhub.paziresh24.com/drapp-client-local
        build:
            context: .
            dockerfile: Dockerfile.localCenter
        environment:
            - NODE_ENV=production
        ports:
            - '4030:80'
