---
- name: Staging DRApp Frontend
  hosts: stage_server
  
  tasks:
    - name: ensure required pip-packages are installed
      pip:
        name:
          - docker>=1.8.0
          - PyYAML>=3.11
          - docker-compose>=1.7.0
        state: present
        executable: pip3

    - name: Check is docker-compose installed
      shell: command -v docker-compose >/dev/null 2>&1
      register: is_docker_compose_install
    - debug: msg="{{ is_docker_compose_install.rc }}" # it returns rc 1
    - debug: var=is_docker_compose_install

    - name: pull
      shell: docker pull docker.paziresh24.info/drapp:latest



    - name: down
      docker_compose:
        project_src: /var/www/fti.cicd/staging/drapp
        files:
          - docker-compose.yml
        state: absent

    - name: up
      docker_compose:
        project_src: /var/www/fti.cicd/staging/drapp
        files:
          - docker-compose.yml
        state: present
